mutation CreateReview($reviewContent: String!, $rating: Int!, $id: ID!) {
  createReview(
    data: { content: $reviewContent, rating: $rating, laptop: $id }
  ) {
    data {
      id
      attributes {
        content
        rating
        laptop {
          data {
            id
          }
        }
      }
    }
  }
}
