query Desktops {
  desktops {
    data {
      id
      attributes {
        model
        longDescription
        inStock
        price
        specifications
        custom_field {
          title
          required
          options
        }
        picture {
          data {
            attributes {
              url
            }
          }
        }
      }
    }
  }
}
