query Desktop($id: ID!) {
  desktop(id: $id) {
    data {
      id
      attributes {
        model
        inStock
        price
        type
        info
        specifications
        longDescription
        custom_field {
          title
          required
          options
        }
        picture {
          data {
            attributes {
              url
            }
          }
        }
      }
    }
  }
}
