query Laptops {
  laptops {
    data {
      id
      attributes {
        model
        Date
        type
        description
        inStock
        price
        specifications
        picture {
          data {
            attributes {
              url
            }
          }
        }
      }
    }
  }
}
