query Laptop($id: ID!) {
  product: laptop(id: $id) {
    data {
      id
      attributes {
        model
        inStock
        price
        type
        specifications
        longDescription
        custom_field {
          title
          required
          options
        }
        description
        info
        picture {
          data {
            attributes {
              url
            }
          }
        }
      }
    }
  }
}
